### PR TITLE
feat: remove home page from documentation website

### PR DESCRIPTION
**Pull request by Valerioageno**

### CODE REVIEW

**Comment by Valerioageno** [comment]
@marcalexiei could you please help me out with the eslint configuration for the doc?  🙏🏽

**Comment by marcalexiei** [comment]
Related to #185.
The fix will take 2 steps:
- fix `apps/documentation`
- review trigger `paths` on all workflows and and include relevant root files that might affect changes inside `packages` folder (e.g.: `package.json` in root)

**Comment by marcalexiei** [comment]
Pending:
- #188 
- #189

Once those 2 PR's are merged we can update these branch and check that everything works!

**Review by marcalexiei — APPROVED** [review]
Added some fix related to `ESLint@9`. We are good to go.

**Pull request merged**
